### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by aelharda** [Zoe-Soen/cheap-flights-checker#1]
can you make a noob ready readme, very intrested in this, so far i got the api for tequila and google sheets but i don't know excactly where to place the google sheets api. Thank you in advance

**Comment by Zoe-Soen** [comment]
Hi @aelharda
Thank you very much for your comment.
I just added the step-by-step settings for Google sheets, please check it out.
I'm a noob, hopefully this doc may help you to understand where and how place the google sheets api now.
Let me know if there's any unclear, I will try to update it accordingly.

**Comment by aelharda** [comment]
Hi @Zoe-Soen , thank you for updating the readme, looking forward to your future optimizations.
